(define (problem india-tour-plan)
  (:domain travel-planner)
  (:init
    (user_ready)
    (want_multi_city_route)
    (want_goa)
    (want_jaipur)
    (want_varanasi)
    (goal_relaxation)
    (prefer_train)
    (hotel_standard)
    (depart_chennai)
  )
  (:goal
    (and
      (destination_selected)
      (beach_activity_booked)
      (transport_reserved)
      (hotel_reserved)
      (itinerary_ready)
      (trip_confirmed)
    )
  )
)